from django.db import models


class FlowInfo(models.Model):
    '''监听流程记录状态为已完成的数据'''
    flow_id = models.CharField(max_length=64, null=True,blank=True, verbose_name="流程id")
    data = models.JSONField(null=True, blank=True, verbose_name="data")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    # status = models.DateTimeField(null=True, blank=True, verbose_name="流程记录的状态")
    # journey_id = models.CharField(max_length=64, null=True, blank=True, verbose_name="流程记录journey_id")
    # name = models.CharField(max_length=64, null=True, blank=True, verbose_name="发起人")
    # workFormNo = models.CharField(max_length=64, null=True, blank=True, verbose_name="工单号")
    # handle_unit = models.CharField(max_length=64, null=True, blank=True, verbose_name="处置科室/社区")
    # wsTopic = models.CharField(max_length=64, null=True, blank=True, verbose_name="来电主题/内容主题")
    # fmContent = models.CharField(max_length=64, null=True, blank=True, verbose_name="来电内容/内容描述")
    # fromName = models.CharField(max_length=64, null=True, blank=True, verbose_name="来电人/来信人")
    # fmAddress = models.CharField(max_length=64, null=True, blank=True, verbose_name="地址")
    # fromTelA = models.CharField(max_length=64, null=True, blank=True, verbose_name="联系电话")
    # bkLimit = models.CharField(max_length=64, null=True, blank=True, verbose_name="办结时限")
    # cDate = models.CharField(max_length=64, null=True, blank=True, verbose_name="来信时间")
    # remark = models.CharField(max_length=64, null=True, blank=True, verbose_name="备注")
    # fmAreaName = models.CharField(max_length=64, null=True, blank=True, verbose_name="区域")
    # SC = models.CharField(max_length=64, null=True, blank=True, verbose_name="商圈")
    # company = models.CharField(max_length=64, null=True, blank=True, verbose_name="投诉公司")
    # smSex = models.CharField(max_length=64, null=True, blank=True, verbose_name="性别")
    # wsCode = models.CharField(max_length=64, null=True, blank=True, verbose_name="流水号")
    # openFrom = models.CharField(max_length=64, null=True, blank=True, verbose_name="网上公开/同意公开")
    # openX = models.CharField(max_length=64, null=True, blank=True, verbose_name="建议公开")
    # iptWorker = models.CharField(max_length=64, null=True, blank=True, verbose_name="创建人")
    # iptTime = models.CharField(max_length=64, null=True, blank=True, verbose_name="创建时间")
    # setProName = models.CharField(max_length=64, null=True, blank=True, verbose_name="工单性质")
    # wfLimit = models.CharField(max_length=64, null=True, blank=True, verbose_name="拟办时间")
    # dfmClaName = models.CharField(max_length=64, null=True, blank=True, verbose_name="来电类别/来信类别/诉求")
    # dcntAname = models.CharField(max_length=64, null=True, blank=True, verbose_name="内容类别")
    # spareString = models.CharField(max_length=64, null=True, blank=True, verbose_name="信件来源")
    # fmEmail = models.CharField(max_length=64, null=True, blank=True, verbose_name="电子邮箱")
    # repeatFlag = models.CharField(max_length=64, null=True, blank=True, verbose_name="判重")
    # wsKey = models.CharField(max_length=64, null=True, blank=True, verbose_name="查询码")
    # setevent_source = models.CharField(max_length=64, null=True, blank=True, verbose_name="工单来源")
    # flowsource = models.CharField(max_length=64, null=True, blank=True, verbose_name="事件来源")
    # next_dept = models.CharField(max_length=64, null=True, blank=True, verbose_name="事件状态")
    # suggestion = models.CharField(max_length=64, null=True, blank=True, verbose_name="派单管家建议派单部门")
    # evidence1 = models.CharField(max_length=64, null=True, blank=True, verbose_name="派单依据1")
    # evidence2 = models.CharField(max_length=64, null=True, blank=True, verbose_name="派单依据2")
    # evidence3 = models.CharField(max_length=64, null=True, blank=True, verbose_name="派单依据3")